#!/usr/bin/env python3
'Program to copy one or more TAP files to specified Topfield PVR host.'
# (C) Mark Blakeney, Mar 2012.

import sys
import argparse
import ftplib
from pathlib import Path

PROG = '/ProgramFiles'
AUTO = PROG + '/AutoStart'
USER = 'guest'
PASS = '0000'

def main():
    'Main code'
    # Process command line options
    opt = argparse.ArgumentParser(description=__doc__.strip(),
            formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    opt.add_argument('-u', '--user', default=USER,
            help='ftp login user name')
    opt.add_argument('-p', '--password', default=PASS,
            help='ftp login user password')
    opt.add_argument('-n', '--noauto', action='store_true',
            help=f'put tapfile[s] in "{PROG}" dir rather than "{AUTO}"')
    opt.add_argument('host',
            help='Topfield PVR IP host name/address')
    opt.add_argument('tapfile', nargs='+',
            help='1 or more TAP files to copy')
    args = opt.parse_args()

    # Connect to host
    try:
        ftp = ftplib.FTP(args.host, args.user, args.password)
    except Exception:
        sys.exit(f'Can not connect to "{args.host}"')

    # Transfer TAP files ..
    tdir = PROG if args.noauto else AUTO
    ftp.cwd(tdir)
    for tapstr in args.tapfile:
        tap = Path(tapstr)

        if not tap.is_file():
            sys.exit(f'No file {tap}')

        print(f'Copying "{tap}" to {args.host}:{tdir}/ ..')
        with tap.open('rb') as fp:
            ftp.storbinary(f'STOR {tap.name}', fp)

    ftp.close()
    sys.exit(error_code)

if __name__ == '__main__':
    main()
